### ISSUE TITLE
consider using withStateHandlers instead of withState and withHandlers

### ISSUE THREAD

**Issue by jbreckel** [signavio/mix-me#5]
`recompose` now offers a very handy way to deal with multiple state entries:
https://github.com/acdlite/recompose/blob/master/docs/API.md#withstatehandlers

We should discuss changing that in our code

https://github.com/signavio/mix-me/blob/69afa92b4b0704af3cc33df415379cc0d68bff48/client/src/Register.js#L55-L66

**Comment by jbreckel** [comment]
https://github.com/signavio/mix-me/blob/960b5b85a4565cba9973f491dd53d95c8d8bfa4b/client/src/Register.js#L55-L66

would become:
```
export default compose(
  withStateHandlers(props => ({ //can be object or function that gets props
    registered: false, // or something out of the props
    username: null, // same here
  }, // first arg is the new state
  { // second arg are the handler functions
    // return higher order functions, first function gets (state, props)
    // returned function is given into props
    onChange: (state, props) => event => ({
      username: event.target.value,
    }),
    onSubmit: (state, props) => event => {
      console.log(state.username)
      return { registered: true }
    },
  })
)
```

**Comment by HermanDahlen** [comment]
Looks great, Ill implement that today

**Comment by jbreckel** [comment]
you could have the `registered` state before with a `withState` and use the `setRegistered` function when the promise is resolved.

https://github.com/acdlite/recompose/issues/443
